spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${USER_DB}
    url: jdbc:mysql://localhost:3306/ecommerce-db?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    password: ${PASS_DB}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: Product Service
server:
  port: '8082'

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}

whitelist:
  paths:
    - "/swagger-ui/**"
    - "/v3/api-docs/**"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  info:
    title: Product Service Api
    version: 1.0.0
    description: Documentation about product operations
